### ISSUE TITLE
Thank you. This is the most exciting code for the esp8266.

### ISSUE THREAD

**Issue by omersiar** [jjssoftware/iD8266#1]
Thank you for sharing this.

* Missing gitignore for node.js
* Missing License information
* I guess it can be built by Platformio and Node + Gulp
* WebServer and WebSocket are these coded from scratch?

**Comment by bebo-dot-dev** [comment]
Hi @omersiar 

* I think you're right that the [node_modules](https://github.com/jjssoftware/iD8266/tree/master/node_modules) directory structure is bloat that can be excluded from this repo. Under normal circumstances this directory structure is populated / maintained by gulp when resource minification is performed.
* I've added an MIT license for maximum permissiveness 
* I have no experience with PlatformIO. So far this code has been maintained with Eclipse Neon with the arduino-eclipse-plugin from here: https://github.com/Sloeber/arduino-eclipse-plugin. I see no reason why PlatformIO wouldn't work though and I expect it will just need whatever configuration files are required for PlatformIO to get things building. To help (I hope), I've added a list of library dependencies to the [README.md](https://github.com/jjssoftware/iD8266/blob/master/README.md) that this project currently depends on.
* The web server:
   * This is an [ESP8266 arduino core](https://github.com/esp8266/Arduino) [ESP8266WebServer](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer) class instance.
* The web socket server
   * This is an [arduinoWebSockets](https://github.com/jjssoftware/arduinoWebSockets) [WebSocketsServer](https://github.com/jjssoftware/arduinoWebSockets/tree/master/src) class instance.

**Comment by omersiar** [comment]
Thank you for your detailed answers. Do you have a compiled binaries? for ESP-12E at least? I want to give it a try. I never used the Eclipse before.

**Comment by bebo-dot-dev** [comment]
Sure I'll build an official v1.0 release and I'll upload it soon.

**Comment by bebo-dot-dev** [comment]
@omersiar here you go:

https://github.com/jjssoftware/iD8266/releases/tag/v1.0

iD8266.bin is the built firmware ready for flashing
The stuff in data.zip / data.tar.gz is the html/css/js which also needs flashing

Let me know if you get stuck

**Comment by omersiar** [comment]
I have flashed the firmware and SPIFFS web files, did not see any trouble, but i have some feedback, let me note them down and share with you.

* Network scanning would be nice for first setup, https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/scan-class.rst#scannetworksasync

You can start a Network Scan via HTTP request and respond with a JSON message.

```c
void printScanResult(int networksFound) {
        DynamicJsonBuffer jsonBuffer;
        JsonObject& root = jsonBuffer.createObject();
        root["command"] = "ssidlist";
        JsonArray& scan = root.createNestedArray("list");
        for (int i = 0; i < networksFound; ++i) {
                JsonObject& item = scan.createNestedObject();
                // Print SSID for each network found
                item["ssid"] = WiFi.SSID(i);
                item["bssid"] = WiFi.BSSIDstr(i);
                item["rssi"] = WiFi.RSSI(i);
                item["channel"] = WiFi.channel(i);
                item["enctype"] = WiFi.encryptionType(i);
                item["hidden"] = WiFi.isHidden(i) ? true : false;
        }
        size_t len = root.measureLength();
        AsyncWebSocketMessageBuffer * buffer = ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
        if (buffer) {
                root.printTo((char *)buffer->get(), len + 1);
                ws.textAll(buffer);
        }
        WiFi.scanDelete();
}
```

**Comment by bebo-dot-dev** [comment]
It's good to hear you've had success getting it running.

Thanks for your feedback. Yes that sounds nice, a WiFi scan feature is something that I've considered would be an improvement to the network settings page for a while - it would make it a little bit easier for a widget to connect to an AP when being configured in STA mode:

https://github.com/jjssoftware/iD8266/blob/master/screenshots/Screenshot_20180131-234540.png

I do think this is a worthwhile change and I will have a go at implementing it asap.

There's also another change implied in your snippet above which is the use of the ArduinoJson library. I know this is a really good idea because it would clean up a lot of hand cranked JSON code that currently exists in https://github.com/jjssoftware/iD8266/blob/master/webserver.cpp

https://github.com/bblanchon/ArduinoJson

This one would be a reasonably large refactor when undertaken. Definitely worth doing.

**Comment by omersiar** [comment]
In my RFID project I use JSON data exchange a lot on WebSocket communication, nearly everything that exchanged between ESP and the Browser is a JSON object, WebSocket communication really simplifies two-way communication, and JSON makes faster web pages development.

Check it out here: https://github.com/omersiar/esp-rfid (You will find a messy code, since i'm still a learner)

**Comment by bebo-dot-dev** [comment]
@omersiar that's a really great project, congratulations! I can see that it's access control related but I can't admit to having an understanding about what RFID is exactly or how the hardware would be arranged with your system to enable access control. I'm sure it would be pretty easy to understand with a little picture or two though. 

You might be interested to hear that I've now added support for building iD8266 with platformIO. The code has been restructured to better fit with platformIO and I've included a platformio.ini to take care of automatically installing all of the required library dependencies.

**Comment by bebo-dot-dev** [comment]
I'm closing this because I don't think there's anything left here to answer here now for the moment.

btw I do have further development in progress at the moment along the lines of introducing the WiFi scan feature that you suggested, switchable firmware features via compiler directives and also a large codebase refactor to move to using ArduinoJson..coming soon

Feel free to open another issue if you see / have problems

**Comment by omersiar** [comment]
I have a video actually, better than pictures.
https://www.youtube.com/watch?v=4F4sQwcSqDQ

RFID Tags are simply identification cards which can be read by an electronic reader. This way information can be exchanged very easily and fast (as in city's transportation cards, corporate badges, etc) As information can be easily passed to a device (like a vending machine or a door) its users can unlock doors, get a sandwich or hop to metro.

With the esp-rfid project, people can build a hardware (with cheap ESP8266 and MFRC522 reader) to accept these RFID tags in order to give access those sources.

People are already using it world-wide, some are built dedicated hardware for it. 
https://www.tindie.com/products/nardev/esp-rfid-board-for-wiegand-readers-at-5v-to-28v/ (only this one is available for buying)

https://www.guesty.com/electronic-smart-locks-for-your-airbnb/

I started esp-rfid project to ultimately get where it can be used to accept payments (with electronic cash or digital contract) and give access to whatever people would like to give access.

https://slock.it/
