### ISSUE TITLE
 Ntp.cpp:37: error: 'setSyncProvider' was not declared in this scope (no idea why)

### ISSUE THREAD

**Issue by RudyFiero** [jjssoftware/iD8266#6]
I don't understand why I get this error. I looked in the library and I did find the function. I shut down Arduino and then deleted the Time library. I downloaded the latest. I started Arduino again, I installed the library again with Add Zip file. I then compiled and got the following error again. 

I am using Arduino 1.85 and ESP8266 2.4.0

```
C:\Users\Rudy\AppData\Local\Temp\arduino_build_323143\sketch\Ntp.cpp: In constructor 'Ntp::Ntp(uint8_t, int8_t, time_t)':

Ntp.cpp:37: error: 'setSyncProvider' was not declared in this scope

  setSyncProvider(getNtpTime);

                            ^
```

I loaded a Time esp8266 sample sketch that has the above function call and it worked just fine. At this point I don't know what to do. 

Well, not quite true. I could install everything again from scratch on a clean computer and try it again. I could use my work machine but once the end of the day comes I want to get out of there as soon as possible.

**Comment by bebo-dot-dev** [comment]
I'm not sure what's going on here either but it does appear to be a path related problem for Time.h -> TimeLib.h. It could be a windows only type of problem but unfortunately I don't have a windows machine to test with here at the moment.

Can you please try this temporary change on [line 13 in the Ntp.h file](https://github.com/jjssoftware/iD8266/blob/master/Ntp.h#L13) and let me know if it has any effect. Change this:

`#include "Time.h"`

..to this:

`#include <TimeLib.h>`

**Comment by RudyFiero** [comment]
That worked. After that it completed the compile without errors.

**Comment by bebo-dot-dev** [comment]
@RudyFiero thanks, I've committed this change as fix https://github.com/jjssoftware/iD8266/commit/a5b3f02d6e990c194de98a7a5c6cec712504636a

I suspect this was a windows specific issue due to windows having a non-case sensitive file system. Some other Time.h file was likely being picked up at build time rather than the intended Time.h file from the https://github.com/PaulStoffregen/Time library.

**Comment by RudyFiero** [comment]
After I tried your suggestion I looked at the example file Time / examples / TimeNTP_ESP8266WiFi / TimeNTP_ESP8266WiFi.ino  and saw that #include <TimeLib.h> was used rather than Time.h and this is why it compiled for me before. 

Thanks for your help. I am looking forward to trying the code when I get home tonight. I was only able to confirm the compile before I went to work this morning.

**Comment by bebo-dot-dev** [comment]
After digging some more it would appear that there's some mystery in the history of the Time.h header file:

https://github.com/PaulStoffregen/Time/blob/master/Time.h

https://github.com/PaulStoffregen/Time/commit/26cd0c85095d5dbfffded0831abb2f7abaad0469

The record shows that once upon a time `Time.h` was the real header file for this library and then something changed around the Arduino 1.6.6 release where it became necessary to change this file to simply become a shim redirect to `TimeLib.h`.

The slightly odd thing is that a header reference to `Time.h` still does work on linux nowadays but it doesn't seem to work on windows at all any more and I suspect this is one of the things that https://github.com/PaulStoffregen/Time/commit/26cd0c85095d5dbfffded0831abb2f7abaad0469 fixed back in November 2015.

Anyway it's problem a solved in this project now. As you say `<TimeLib.h>` does appear to be the correct and consistent way of referencing this library nowadays.

Thanks again and good luck.

**Comment by RudyFiero** [comment]
So close. I see the AP iD8266 but I need a password to connect, but I can't find any reference to it.

**Comment by bebo-dot-dev** [comment]
The default password for both the AP and for web login upon initial login is `password1234`

https://github.com/jjssoftware/iD8266/blob/master/iD8266/flashAppData.h#L21

https://github.com/jjssoftware/iD8266/blob/master/screenshots/Screenshot_20180131-234517.png

Once you've connected to the AP, the AP IP is the default 192.168.4.1 and you should be able to see the login page if you navigate to http://192.168.4.1 in a browser

When you login for the first time you will be prompted to change the default password and when you do this, it will change the password for both the AP and also the admin web logon account to your new password.

Edit: I've started building the project wiki here: https://github.com/jjssoftware/iD8266/wiki
